name: CI Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: # Give the job a descriptive name
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout Code # Clear step name
        uses: actions/checkout@v3

      - name: Install Dependencies # Clear step name
        run: |   # Multi-line command for readability
          pip install --upgrade pip
          pip install -r requirements.txt 
          pip install flake8

      - name: lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics  
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit test with nose
        run: 
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
